### ISSUE TITLE
Execute your First model tutorial doesn't match Train mdoel

### ISSUE THREAD

**Issue by m3rlin45** [facebookresearch/pytext#129]
## Steps to reproduce
in the docs:
The example used in "train your first model" is docnn for alarm intent, however the example used for "execute your first model" is using ATIS, the gap in the example categories is confusing. We should make it match the docnn results for "train your first model" because:

* Users who are following the tutorials in order will expect it
* Users coming to this tutorial from ATIS will have a better understanding and be less likely to get confused by the mismatch, as they have already  gained some experience

**Comment by snisarg** [comment]
Looking at this.

**Comment by snisarg** [comment]
Do we need to talk about ATIS on this page at all? As you said, coming to this page from ATIS are advanced users who know that the config file will change to the one they're currently playing with instead of the DocNN one. 

I propose we get rid if any mention of ATIS on https://pytext-pytext.readthedocs-hosted.com/en/latest/execute_your_first_model.html, and replace the "Evaluate the model" output with the DocNN one.
