### ISSUE TITLE
Running out of memory when training a language model

### ISSUE THREAD

**Issue by mghmgh1281375** [facebookresearch/pytext#462]
## Steps to reproduce

  1. pytext train < language_model.json

## Observed Results

  Runing out of memory on loading dataset phase. (used memory ~ 40GB)
  all_text_lined_light_train.txt    1.9G
  all_text_lined_light_test.txt    242M

## Relevant Code
language_model.json
  ```
{
  "task": {

    "LMTask": {
      "trainer": {
        "epochs": 1,
        "early_stop_after": 0,
        "max_clip_norm": null,
        "report_train_metrics": true
      },
      "data_handler": {
              "LanguageModelDataHandler":{
                "train_path": "resources/all_text_lined_light_train.txt",
                "eval_path": "resources/all_text_lined_light_test.txt",
                "test_path": "resources/all_text_lined_light_test.txt",
                "train_batch_size": 1,
                "eval_batch_size": 1,
                "test_batch_size": 1,
                "columns_to_read": [
                        "text"
                ]
              }
      },
      "model": {
         "representation": {
                "save_path": "resources/all_text_language_model_representation.weights"
         }
      }
    }
  },
  ...
}
  ```

**Comment by mwu1993** [comment]
Unfortunately, this seems possible at the moment, as the framework is not super memory-efficient. In the new data design (e.g. https://github.com/facebookresearch/pytext/blob/master/demo/configs/new_docnn.json), the data should be streamed instead of being fully loaded into memory, which should help. The LM task hasn't been migrated though :(

**Comment by puttkraidej** [comment]
I faced the same issue too
my training set is less than 5G and I have 32G for memories :(

**Comment by Titousensei** [comment]
The new data design with streaming is out with v0.2.0. Please try it and let us know if it solves your issue.

**Comment by puttkraidej** [comment]
@Titousensei, thank you very much
I tried v0.2.0 according to your advise, unfortunately I got this error message

> tokens, seq_lens = tensor_dict["tokens"]
> ValueError: too many values to unpack (expected 2)

my config file is 

            "TSVDataSource": {
              "column_mapping": {},
              "delimiter": "\t",
              "eval_filename": "file",
              "field_names": ["text"],
              "test_filename": "file",
              "train_filename": "file"
            }

After that I tried
$pytext update-config <my_config_file>
to transform my old version of config file to match with v0.2.0 and now above errors disappear. Anyway, my task has been killed because my data (only 10k text lines) cannot fit in the memory (32G of RAM)

**Comment by borguz** [comment]
Can you try setting this to false: https://github.com/facebookresearch/pytext/blob/975f31f6f6e06688eaa0fafc93eef33c8a55e1d1/pytext/data/data.py#L204

**Comment by jeanm** [comment]
Closing this issue as stale. Please feel free to reopen if the problem persists even with the config change suggested above.
